version: '3.9'
services:
  nginx:
    image: nginx-valis:latest
    container_name: nginx-valis
    build:
      context: nginx
    volumes:
      - ${VALIS_SOCKET_DIR:-/tmp/valis}:/tmp/valis # (host_socket_dir:upstream_socket_location)
    ports:
      - 5000:8080
    networks:
      - valisnet

  valis:
    build:
      context: valis
    image: valis:0.1.0
    container_name: valis
    volumes:
      - ${VALIS_SOCKET_DIR:-/tmp/valis}:/tmp/valis # (host_socket_dir:container_socket_dir)
    networks:
      - valisnet

networks:
  valisnet:


